config/routes.rb
Rails.application.routes.draw do
  get 'pages/lose'

  get 'pages/win'

  get 'pages/home'

  get 'pages/l1left'

  get 'pages/l1right'

  get 'pages/l2jump'

  get 'pages/l2pinkdoor'

  get 'pages/l3continue'

  get 'pages/l3openchestright'

  get 'pages/l3continueright'

  get 'pages/l4green'

  get 'pages/l4red'

  get 'pages/l4left'

  root to: 'pages#home'
  
  get 'pages/lose'

  get 'pages/win'

  get 'pages/home'
  
  get 'pages/l3pet'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def lose
  end

  def win
  end

  def home
  end

  def l1left
  end

  def l1right
  end

  def l2jump
  end

  def l2pinkdoor
  end

  def l3continue
  end

  def l3openchestright
  end

  def l3continueright
  end

  def l4green
  end

  def l4red
  end

  def l4left
  end

  def l3pet
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Electronquest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
<div class="panel panel-default">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<div class='panel-heading'>
  <h1>Welcome to......</h1>
  <h1>Electron Quest!</h1>
</div>

<div class='panel-body'>
  <%= image_tag("hydrogen.jpg",  height: "100") %>
  <p>You are a Hydrogen Atom going on an epic quest to get an electron so that you have
  a full valence shell and you are stable and happy! Better get going!</p>
  <p> In this game you have 2 choices and whatever choice you make leads to more choices -
  There are 3 different paths to victory, try to find them all!</p>
  <%= image_tag("Two way tunnel.jpg",  height: "100") %>
  <p>You come across a two way cavern - do you go left, or right?</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "left" ,pages_l1left_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
  <div style='float: left; width: auto;'>
    <%= button_to "right" , pages_l1right_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - The atomic number is the same as the number of protons and electrons in a neutral atom!</H3>
</div>

app/views/pages/l1left.html.erb
<div class='panel-heading'>
  <h1>You chose left</h1>
</div>

<div class='panel-body'>
  <%= image_tag("Lava.jpg",  height: "100") %>
  <p>You come across a lava pool. Do you jump across or go back?</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "Jump" ,pages_l2jump_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
  <div style='float: left; width: auto;'>
    <%= button_to "Go Back" , pages_lose_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - The atomic number plus the number of neutrons equals the atomic weight!</H3>
</div>

app/views/pages/l1right.html.erb
<div class='panel-heading'>
  <h1>You chose right</h1>
</div>

<div class='panel-body'>
  <%= image_tag("PinkDoorHeart.PNG",  height: "100") %> <%= image_tag("BatCave.jpg",  height: "100") %>
  <p>You find two paths; a creepy bat cave, and a pink door with a heart. Do you go through the pink door or into the cave?</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "Bat Cave" ,pages_lose_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
  <div style='float: left; width: auto;'>
    <%= button_to "Pink Door" , pages_l2pinkdoor_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - The first group on the periodic table, called the alkali metals, are the most reactive!</H3>
</div>

app/views/pages/l2jump.html.erb
<div class='panel-heading'>
  <h1>You chose jump</h1>
</div>

<div class='panel-body'>
    <%= image_tag("Treasure chest.jpg",  height: "100") %>
  <p>You succsessfully made it across the lava pit.You then come across a treasure chest. Do you open the chest or continue on your way?</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "Open" ,pages_lose_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
  <div style='float: left; width: auto;'>
    <%= button_to "Continue" , pages_l3continue_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - Group 8  on the periodic table, or the noble gases, have a full valence shell and therefore do not want to react with any other element!</H3>
</div>

app/views/pages/l2pinkdoor.html.erb
<div class='panel-heading'>
  <h1>You chose the pink door</h1>
</div>

<div class='panel-body'>
  <%= image_tag("Treasure chest.jpg",  height: "100") %>
  <p>You find a chest. Do you open it or continue on?</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "Open" ,pages_l3openchestright_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
  <div style='float: left; width: auto;'>
    <%= button_to "Continue" , pages_l3continueright_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - The periodic table is made up of metals, non-metals, and metalloids!</H3>
</div>

app/views/pages/l3continue.html.erb
<div class='panel-heading'>
  <h1>You chose to continue.</h1>
</div>

<div class='panel-body'>
  <%= image_tag("Green door.jpg",  height: "100") %> <%= image_tag("Red door.jpg",  height: "100") %>
  <p>You come across two doors, green and red. Which one do you go through?</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "Green" ,pages_l4green_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
  <div style='float: left; width: auto;'>
    <%= button_to "Red" , pages_l4red_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - The most common catagory in the periodic table is metals!</H3>
</div>

app/views/pages/l3continueright.html.erb
<div class='panel-heading'>
  <h1>You chose to continue</h1>
</div>

<div class='panel-body'>
  <%= image_tag("Two way tunnel.jpg",  height: "100") %>
  <p>You find yourself at an intersection. Do you go left or right?</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "Left" ,pages_l4left_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
  <div style='float: left; width: auto;'>
    <%= button_to "Right" , pages_lose_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - Metalloids have characteristics of metals and non metals!</H3>
</div>

app/views/pages/l3openchestright.html.erb
<div class='panel-heading'>
  <h1>You chose to open the chest.</h1>
</div>

<div class='panel-body'>
  <%= image_tag("PetDog.jpg",  height: "100") %>
  <p>You found a cute doggy! :)</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "Continue on" ,pages_l3pet_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Fun Fact - There are 118 elements on the periodic table!</H3>
</div>

app/views/pages/l3pet.html.erb
<div class='panel-heading'>
  <h1>You have a pet!</h1>
</div>

<div class='panel-body'>
  <%= image_tag("PetDog.jpg",  height: "100") %>
  <%= image_tag("Two way tunnel.jpg",  height: "100") %>
  <p>You come across a two way intersection, but your dog smells the right way as dangerous.</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "Left" ,pages_l4left_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - If you take away an electron from an atom, it becomes a positively charge cation!</H3>
</div>

app/views/pages/l4green.html.erb
<div class='panel-heading'>
  <h1>You chose the green door</h1>
</div>

<div class='panel-body'>
  <%= image_tag("Beggar.jpg",  height: "100") %>
  <p>You find a lonely beggar with a tin can for spare coins. Do you give him your spare money or walk away?</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "Give Coins" ,pages_win_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
  <div style='float: left; width: auto;'>
    <%= button_to "Walk Away" , pages_lose_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - If you put another electron into an atom, it becomes a negatively charged anion!</H3>
</div>

app/views/pages/l4left.html.erb
<div class='panel-heading'>
  <h1>You chose left</h1>
</div>

<div class='panel-body'>
  <%= image_tag("GameHost.jpg",  height: "100") %>
  <p>You come into a room with a game show host in it. He asks you a SCIENCE QUESTION! OH NO! You must answer to continue.</p>
  <p>The question is - "True or false: The number of protons are always the same as the number of neutrons in any atom."</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "True" ,pages_lose_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
  <div style='float: left; width: auto;'>
    <%= button_to "False" , pages_win_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - The largest group on the periodic table is the transition metals!</H3>
</div>

app/views/pages/l4red.html.erb
<div class='panel-heading'>
  <h1>You chose red.</h1>
</div>

<div class='panel-body'>
  <%= image_tag("PillCat.jpg",  height: "300") %>
  <p>You come up to a cat that offers you 2 pills - A red one and a blue one. Which one do you take?</p>

  <div style='float: left; width: 100px;'>
    <%= button_to "Red" ,pages_win_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
 
  <div style='float: left; width: auto;'>
    <%= button_to "Blue" , pages_lose_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - The atom with the atomic number of 1 is hydrogen!</H3>
</div>

app/views/pages/lose.html.erb
<div class='panel-heading'>
  <h1>Oh no! You lose!</h1>
</div>

<div class='panel-body'>
  <%= image_tag("hydrogenbomb.jpg",  height: "199") %>
  <p>Sorry, you've become unstable!</p>

  <div style='float: left; width: auto;'>
    <%= button_to "Play Again?" , pages_home_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Tip - The 2 rows below the periodic table are radioactive!</H3>
</div>

app/views/pages/win.html.erb
<div class='panel-heading'>
  <h1>Hooray! You win!!!</h1>
</div>

<div class='panel-body'>
  <%= image_tag("ElectronWin.jpg",  height: "200") %>
  <p>You've surived the epic quest to become a stable hydrogen atom!!</p>

  <div style='float: left; width: auto;'>
    <%= button_to "Play Again?" , pages_home_path, :method=>:get, :class => 'btn btn-primary' %>
  </div>
</div>
<br/>
<div class='well well-lg'>
  <H3>Science Fun Fact - Ununoctium is the element with the highest atomic number - at 118!</H3>
</div>